/*
 * This source file was generated by the Gradle 'init' task
 */
package blockchain;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class App {
    public static void main(String[] args) throws IOException {
        int port;
        BufferedReader consoleReader = new BufferedReader(new InputStreamReader(System.in));

        System.out.println("Enter port number for this node: ");
        port = Integer.parseInt(consoleReader.readLine());

        Node node = new Node(port);
        node.startServer();

        System.out.println("Type 'connect <host> <port>', 'send <PublicKey> <message>', 'mine', 'chain' or 'exit'");
        String input;
        while((input = consoleReader.readLine()) != null) {
            if("exit".equalsIgnoreCase(input)) {
                break;
            }
            if (input.startsWith("connect ")) {
                try {
                    String[] parts = input.split(" ");
                    String host = parts[1];
                    int peerPort = Integer.parseInt(parts[2]);

                    node.connectToPeer(host, peerPort);
                } catch (Exception e) {
                    System.err.println("Usage: connect <host> <port>");
                }
            } else if (input.startsWith("send ")) {
                try {
                    String[] parts = input.split(" ", 3);
                    String recipientKey = parts[1];
                    String data = parts[2];

                    node.createAndBroadcastTransaction(recipientKey, data);
                } catch (Exception e) {
                    System.err.println("Usage: send <recipient_key> <data>");
                }
            } else if (input.equalsIgnoreCase("mine")) {
                node.startMining();
            } else if (input.equalsIgnoreCase("chain")) {
                System.out.println(node.getBlockchain().toString());
            } else {
                System.out.println("Unknown command. Usage: 'connect...' or 'send...");
            }
            
        }

        System.out.println("Node shutting down..");
        System.exit(0);
    
    }
}


//.\gradlew.bat app:run